# Load config
configfile: "config/config.yaml"

# Include rules
include: "rules/ref.smk"
# include: "rules/qc.smk"
# include: "rules/align.smk"
# include: "rules/bqsr.smk"
# include: "rules/variant.smk"


rule all:
    input:
        config["references"]["genome_fa"] + ".fai",
        config["references"]["genome_fa"].replace(".fa", ".dict")
