base_dir: /home/sson0030/xy86_scratch2/SANJAY/Organoid
sample_id: ORG125

references:
  genome_fa: "{base_dir}/references/GRCh38.primary_assembly.genome.fa"
  dbsnp: "{base_dir}/variant_calling_resources/resources_broad_hg38_v0_Homo_sapiens_assembly38.dbsnp138.vcf"
  mills: "{base_dir}/variant_calling_resources/resources_broad_hg38_v0_Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
  af_gnomad: "{base_dir}/variant_calling_resources/af-only-gnomad.hg38.vcf.gz"

data:
  tumor_r1: "{base_dir}/WES/data/Tumor/ORG125T_Data_L1_1.fq.gz"
  tumor_r2: "{base_dir}/WES/data/Tumor/ORG125T_Data_L1_2.fq.gz"
  normal_r1: "{base_dir}/WES/data/Normal/ORG125N_Data_L1_1.fq.gz"
  normal_r2: "{base_dir}/WES/data/Normal/ORG125N_Data_L1_2.fq.gz"

threads: 16
memory: 19G
